config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  scope 'nico', as: 'nico' do
    root 'nico/top#index'
    get 'search' => 'nico/search#index'
    post 'condition' => 'nico/condition#create'
    delete 'condition/:id' => 'nico/condition#destroy'
    get 'game' => 'nico/game#index'
    post 'game' => 'nico/game#create'
    get 'vocaloid' => 'nico/vocaloid#index'
    get 'utau' => 'nico/utau#index'
  end
end

app/controllers/nico/condition_controller.rb
class Nico::ConditionController < ApplicationController
  before_action :logged_in

  def create
    condition = NicoCondition.new condition_params.merge({ user_id: @user.id })
    raise StandardError, 'Invalid data.' unless condition.valid?

    condition.save
    render json: { result: 'success', data: condition }
  end

  def destroy
    condition = NicoCondition.find(params[:id])
    raise StandardError, 'You don\'t have permission.' if condition.user_id != @user.id

    condition.destroy
    render json: { result: 'success', condition: }
  end

  private

  def condition_params
    params.permit(:query, :limit, :minimum_views)
  end
end

app/controllers/nico/game_controller.rb
class Nico::GameController < ApplicationController
  include NicoApi
  before_action :logged_in

  def index
    nico_game = NicoGame.find_by user_id: @user.id
    if nico_game.nil?
      @videos = []
    else
      @videos = JSON.parse(nico_game.videos, { symbolize_names: true })
      @updated_at = nico_game.updated_at
    end
  end

  def create
    videos = fetch_videos
    save_nico_game(videos)

    redirect_to nico_game_path, notice: '更新しました!!'
  rescue StandardError => e
    redirect_to nico_game_path, notice: "更新に失敗!!: #{e.message}"
  end

  private

  def fetch_videos
    videos = []
    videos.concat(fetch_video(query: 'mtg -mtga -mtgアリーナ', limit: 5, smallest_views: 300))
    videos.concat(fetch_video(query: 'sims -MMD -MikuMikuDance', limit: 5, smallest_views: 100))
    videos.concat(fetch_video(query: 'tropico', limit: 3, smallest_views: 300))
    videos.concat(fetch_video(query: 'cities:skylines', limit: 5, smallest_views: 500))
    videos.concat(fetch_video(query: 'ets2 -MMD -切り抜き', limit: 5, smallest_views: 100))
    videos.sort_by! { |video| video[:startTime] }.reverse!
  end

  def fetch_video(query:, limit:, smallest_views:)
    fetch_nico(query:, limit:, sort: '-startTime', filters:
    {
      viewCounter: { gte: smallest_views },
      startTime: { gte: "#{Date.today.months_ago(1).iso8601}T00:00:00+09:00" }
    })
  end

  def save_nico_game(videos)
    nico_game = NicoGame.find_by user_id: @user.id
    if nico_game.nil?
      nico_game = NicoGame.new
      nico_game.user_id = @user.id
    end
    nico_game.videos = videos.to_json
    nico_game.save
  end
end

app/controllers/nico/search_controller.rb
class Nico::SearchController < ApplicationController
  include NicoApi
  before_action :logged_in

  def index
    @query = params[:query]
    @limit = params[:limit].presence || 10
    @minimum_views = params[:minimum_views].presence || 1000
    filters = { viewCounter: { gt: @minimum_views } }
    @videos = @query.blank? ? [] : fetch_nico(query: @query, limit: @limit, filters:, sort: '-startTime')
    @conditions = NicoCondition.where(user_id: @user.id)
  end

  private

  def test_data
    [
      {
        startTime: '2017-09-10T19:07:24+09:00',
        tags: '7_days_to_die VOICEROID実況プレイ クソリプ４銃士 ゲーム マッスル広告感謝 例のアレ 偽乳特戦隊 東北きりたん実況プレイ 結月ゆかりファンのマッスルサイド 結月ゆかり実況プレイ',
        lengthSeconds: 796,
        viewCounter: 9991,
        contentId: 'sm31901870',
        title: '【7DTD】きりたんとイスになったゆかりんの９脚目α16.3【VOICEROID実況】',
        commentCounter: 261,
        likeCounter: 0,
        thumbnailUrl: 'https://nicovideo.cdn.nimg.jp/thumbnails/31901870/31901870'
      },
      {
        startTime: '2015-06-11T19:33:00+09:00',
        tags: '7days_to_die 7DTD 7_days_to_die VOICEROID実況プレイ ゲーム 弦巻マキ実況プレイ 琴葉茜・葵実況プレイ 結月ゆかり 葵ちゃん＠がんばらない 葵ちゃん＠運が無い 重い葵ちゃん',
        lengthSeconds: 878,
        viewCounter: 9986,
        contentId: 'sm26464385',
        title: '【7Days to die】葵ちゃん＠がんばらない【Part3】',
        commentCounter: 202,
        likeCounter: 1,
        thumbnailUrl: 'https://nicovideo.cdn.nimg.jp/thumbnails/26464385/26464385'
      }
    ]
  end
end

app/controllers/nico/top_controller.rb
class Nico::TopController < ApplicationController
  before_action :logged_in

  def index; end
end

app/controllers/nico/utau_controller.rb
class Nico::UtauController < ApplicationController
  include NicoApi
  before_action :logged_in

  def index
    begin
      @date = params[:date].presence ? Date.parse(params[:date]) : Date.today
    rescue Date::Error
      @date = Date.today
    end
    @videos = fetch @date
  end

  private

  def fetch(date)
    filters = {
      startTime: {
        gte: "#{date.iso8601}T00:00:00+09:00",
        lte: "#{date.iso8601}T23:59:59+09:00"
      },
      viewCounter: {
        gte: 300
      }
    }
    fetch_nico(query: 'utauオリジナル OR utauカバー', limit: 30, filters:)
  end
end

app/controllers/nico/vocaloid_controller.rb
class Nico::VocaloidController < ApplicationController
  include NicoApi
  before_action :logged_in

  def index
    begin
      @date = params[:date].presence ? Date.parse(params[:date]) : Date.today
    rescue Date::Error
      @date = Date.today
    end
    @videos = fetch @date
  end

  private

  def fetch(date)
    filters = {
      startTime: {
        gte: "#{date.iso8601}T00:00:00+09:00",
        lte: "#{date.iso8601}T23:59:59+09:00"
      },
      viewCounter: {
        gte: 3000
      }
    }
    fetch_nico(query: 'VOCALOID オリジナル', limit: 30, filters:)
  end
end

app/controllers/nico_controller.rb
class NicoController < ApplicationController
  before_action :logged_in

  def index; end

  def search
    @query = params[:query]
    @limit = params[:limit].presence || 10
    @minimum_views = params[:minimum_views].presence || 1000
    filters = { viewCounter: { gt: @minimum_views } }
    @videos = @query.blank? ? [] : fetch_nico(query: @query, limit: @limit, filters:, sort: '-startTime')
    @conditions = NicoCondition.where(user_id: @user.id)
  end

  def create_condition
    condition = NicoCondition.new condition_params.merge({ user_id: @user.id })
    rails StandardError, 'Invalid data.' unless condition.valid?
    condition.save
    render json: { result: 'success', data: condition }
  end

  def destroy_condition
    condition = NicoCondition.find(params[:id])
    raise StandardError, 'You don\'t have permission.' if condition.user_id != @user.id

    condition.destroy
    render json: { result: 'success', condition: }
  end

  private

  def condition_params
    params.permit(:query, :limit, :minimum_views)
  end

  def fetch_nico(query:, targets: 'title,description,tags', sort: '-viewCounter', limit: 10, filters: {})
    uri = URI 'https://api.search.nicovideo.jp/api/v2/snapshot/video/contents/search'
    uri.query = build_nico_query(query:, targets:, sort:, limit:, filters:)
    response = HTTP.get uri.to_s
    JSON.parse(response.body.to_s, symbolize_names: true)[:data]
  end

  def build_nico_query(query:, targets:, sort:, limit:, filters:)
    {
      q: query,
      filters:,
      targets:,
      _sort: sort,
      _context: 'rails-nk',
      fields: 'contentId,title,tags,viewCounter,likeCounter,lengthSeconds,thumbnailUrl,commentCounter,startTime',
      _limit: limit
    }.to_param
  end

  def test_data
    [
      {
        startTime: '2017-09-10T19:07:24+09:00',
        tags: '7_days_to_die VOICEROID実況プレイ クソリプ４銃士 ゲーム マッスル広告感謝 例のアレ 偽乳特戦隊 東北きりたん実況プレイ 結月ゆかりファンのマッスルサイド 結月ゆかり実況プレイ',
        lengthSeconds: 796,
        viewCounter: 9991,
        contentId: 'sm31901870',
        title: '【7DTD】きりたんとイスになったゆかりんの９脚目α16.3【VOICEROID実況】',
        commentCounter: 261,
        likeCounter: 0,
        thumbnailUrl: 'https://nicovideo.cdn.nimg.jp/thumbnails/31901870/31901870'
      },
      {
        startTime: '2015-06-11T19:33:00+09:00',
        tags: '7days_to_die 7DTD 7_days_to_die VOICEROID実況プレイ ゲーム 弦巻マキ実況プレイ 琴葉茜・葵実況プレイ 結月ゆかり 葵ちゃん＠がんばらない 葵ちゃん＠運が無い 重い葵ちゃん',
        lengthSeconds: 878,
        viewCounter: 9986,
        contentId: 'sm26464385',
        title: '【7Days to die】葵ちゃん＠がんばらない【Part3】',
        commentCounter: 202,
        likeCounter: 1,
        thumbnailUrl: 'https://nicovideo.cdn.nimg.jp/thumbnails/26464385/26464385'
      }
    ]
  end
end

app/helpers/nico/condition_helper.rb
module Nico::ConditionHelper
end

app/helpers/nico/game_helper.rb
module Nico::GameHelper
  def last_updated
    return unless @updated_at.respond_to?('strftime') && @updated_at.respond_to?('to_datetime')

    diff = DateTime.now - @updated_at.to_datetime
    return '最近' if diff < 0.1

    "#{diff.to_i}日と#{((diff - diff.to_i) * 24).to_i}時間前"
  end
end

app/helpers/nico/search_helper.rb
module Nico::SearchHelper
end

app/helpers/nico/top_helper.rb
module Nico::TopHelper
end

app/helpers/nico/utau_helper.rb
module Nico::UtauHelper
end

app/helpers/nico/vocaloid_helper.rb
module Nico::VocaloidHelper
end

app/views/nico/_head_links.html.erb
<div id='nico-head-links'>
  <span><%= link_to 'Top', root_path %></span> |
  <span><%= link_to 'Search', nico_search_path %></span> |
  <span><%= link_to 'Game', nico_game_path %></span> |
  <span><%= link_to 'Vocalod', nico_vocaloid_path %></span> |
  <span><%= link_to 'Utau', nico_utau_path %></span>
</div>

app/views/nico/_video_row.html.erb
<% video_url = 'https://nico.ms/' + video[:contentId] %>
<div class='video-row'>
  <div class='video-image'>
    <a href='<%= video_url %>' target='_blank'>
      <img src="<%= video[:thumbnailUrl] %>"/>
    </a>
  </div>
  <div class='video-infomations-wrapper'>
    <div class='video-title'>
      <%= link_to video[:title], video_url, { target: '_blank'} %>
    </div>
    <div class='video-counters'>
      <i class="las la-play"></i> <%= video[:viewCounter] %>
      <i class="las la-comment"></i> <%= video[:commentCounter] %>
      <i class="las la-heart"></i> <%= video[:likeCounter]%>
    </div>
    <div class='video-posted-at'><%= DateTime.parse(video[:startTime]).strftime('%Y/%m/%d %H:%M')  %></div>
    <div class='video-tags'><%= video[:tags] %></div>
  </div>
</div>

app/views/nico/search.html.erb
<h1>nico/search</h1>

<%= render partial: 'head_links' %>

<%= form_with id: 'nico-search-form', method: 'GET' do |form| %>
  <table>
    <tbody>
      <tr>
        <td class='label-cell'>
          <%= form.label :query, 'Words' %>
        </td>
        <td>
          <%= form.text_field :query, value: @query %>
        </td>
      </tr>
      <tr>
        <td class='label-cell'>
          <%= form.label :limit, 'Limit' %>
        </td>
        <td>
          <%= form.text_field :limit, type: 'number', value: @limit %>
        </td>
      </tr>
      <tr>
        <td class='label-cell'>
          <%= form.label :minimum_views, 'Minimum views' %>
        </td>
        <td>
          <%= form.text_field :minimum_views, type: 'number', value: @minimum_views, step: 100 %>
        </td>
      </tr>
      <tr>
        <td></td>
        <td>
          <%= form.submit 'Search' %>
          <button id='add-condtion' type='button'>Add</button>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

<div id='condition-list' data-conditions='<%= @conditions.to_json %>'>
</div>

<div id='condition-row-format' class='condition-row'>
  <span class='apply-button'>
    <span class='query'></span> |
    <span class='limit'></span>個 |
    最低<span class='minimum-views'></span>再生
    <button type='button' class='delete-button'>削除</button>
  </span>
</div>

<div class='video-list'>
  <% @videos.each do |video|  %>
    <%= render partial: 'video_row', locals: {video: video } %>
  <% end %>
</div>

<%= javascript_include_tag 'nico_search_form.js' %>